Morefixes
mczerski/SD-card-controller pull request #6
Opened 2019-09-20 07:07 UTC by olofk

A bunch of syntactic fixes to make the tools complain less about the code

2019-10-07 06:23 UTC, mczerski requested changes

2019-10-07 06:23 UTC, mczerski commented on rtl/verilog/sd_cmd_master.v
> +                if (|timeout_reg && watchdog >= timeout_reg) begin
what is the difference here ? To my knowledge, the old version will resolve the left side of the && operator to true only when timeout_reg != 0, and the new version will or every bit of the timeout_reg which becomes true only when timeout_reg != 0. So both versions are semantically the same.

2019-10-07 06:23 UTC, mczerski commented on rtl/verilog/sd_controller_wb.v
> +                `controller: wb_dat_o[0] <= controll_setting_reg;
maybe add constant for width of controll_setting_reg, software_reset_reg, clock_divider_reg and capabilies_reg registers ?

2019-10-08 21:07 UTC, olofk commented on rtl/verilog/sd_cmd_master.v
> +                if (|timeout_reg && watchdog >= timeout_reg) begin
That is correct, but the `&&` expects a boolean one-bit expression on each side and timeout_reg is wider than one bit. This causes the original expression to issue a warning with Verilator.

2019-10-08 21:12 UTC, olofk commented on rtl/verilog/sd_controller_wb.v
> +                `controller: wb_dat_o[0] <= controll_setting_reg;
I could do that in a separate patch if you like so that this patch keeps the focus on just fixing warnings. Would that be ok?

2019-10-09 06:35 UTC, mczerski commented on rtl/verilog/sd_cmd_master.v
> +                if (|timeout_reg && watchdog >= timeout_reg) begin
Hmm, according to SystemVerilog standard (Table 11-1—Operators and data types) the && operator can take Integral, real, shortreal operands and timeout_reg is an integral operator. But if verilator is not conforming to the standard then I guess it is easier to make this change.

2019-10-09 06:36 UTC, mczerski commented on rtl/verilog/sd_controller_wb.v
> +                `controller: wb_dat_o[0] <= controll_setting_reg;
sure, thats ok.

2020-04-17 20:46 UTC, merged